import http from "http";
import path from "path";
import { connect } from "./utilities/database.js";
import { getAbout } from "./routes/about.js";
import { getLogin, loginUser, logoutUser, getAuthentication, authenticateUser } from "./routes/login.js";
import { getProfile, saveProfile, getPassword, savePassword } from "./routes/profile.js";
import { getTfa, generateQrCode, toggleTfa } from "./routes/tfa.js";
import { getItems, saveItem, getItem, deleteItem, pinItem } from "./routes/items.js";
import { saveContact, answerContact } from "./routes/contacts.js";
import { getJsFile, getUtilityFile, getCssFile, getImageFile, getFaviconFile, getNoAccessFile } from "./routes/static.js";
import { isStaticFileAllowed } from "./utilities/scripts.js";
import { ABOUT_TYPE, DOWNLOAD_TYPE, OVERVIEW_TYPE, PROFILE_TYPE, SKILL_TYPE, RESUME_ITEM_TYPE, PORTFOLIO_ITEM_TYPE, CERTIFICATION_TYPE, CUSTOMER_TYPE, CONTACT_TYPE } from "./utilities/types.js";

const BASE_URL = process.env.BASE_URL;
const PORT = process.env.PORT || BASE_URL.split(":")[2];

const server = http.createServer();
await connect();

server.on("request", async (request, response) => {
  const { url, method, headers: { "content-type": contentType } } = request;
  if (url.endsWith(".php")) return response.writeHead(404).end("Not found");
  if (((url === "/") || (url.startsWith("/?language="))) && (method === "GET")) await getAbout(ABOUT_TYPE, request, response);
  else if (url.startsWith("/download?language=") && (method === "GET")) await getAbout(DOWNLOAD_TYPE, request, response);
  else if ((url === "/login") && (method === "GET")) await getLogin(request, response);
  else if ((url === "/loginUser") && (method === "POST") && (contentType === "application/json")) await loginUser(request, response);
  else if ((url === "/logoutUser") && (method === "GET")) logoutUser(response);
  else if ((url === "/authentication") && (method === "GET")) await getAuthentication(request, response);
  else if ((url === "/authenticateUser") && (method === "POST") && (contentType === "application/json")) await authenticateUser(request, response);
  else if ((url === "/overview") && (method === "GET")) await getProfile(OVERVIEW_TYPE, request, response);
  else if ((url === "/profile") && (method === "GET")) await getProfile(PROFILE_TYPE, request, response);
  else if ((url === "/saveProfile") && (method === "PUT") && (contentType === "application/json")) await saveProfile(request, response);
  else if ((url === "/password") && (method === "GET")) await getPassword(request, response);
  else if ((url === "/savePassword") && (method === "PUT") && (contentType === "application/json")) await savePassword(request, response);
  else if ((url === "/tfa") && (method === "GET")) await getTfa(request, response);
  else if ((url === "/toggleTfa") && (method === "POST") && (contentType === "application/json")) await toggleTfa(request, response);
  else if ((url === "/generateQrCode") && (method === "GET")) await generateQrCode(request, response);
  else if ((url === "/skills") && (method === "GET")) await getItems(SKILL_TYPE, request, response);
  else if (url.startsWith("/getSkill/") && (method === "GET")) await getItem(SKILL_TYPE, request, response, path.basename(url));
  else if ((url === "/saveSkill") && (method === "POST") && (contentType === "application/json")) await saveItem(SKILL_TYPE, request, response);
  else if (url.startsWith("/deleteSkill/") && (method === "DELETE")) await deleteItem(SKILL_TYPE, request, response, path.basename(url));
  else if (url.startsWith("/pinSkill/") && (method === "PUT")) await pinItem(SKILL_TYPE, request, response, path.basename(url));
  else if ((url === "/resume") && (method === "GET")) await getItems(RESUME_ITEM_TYPE, request, response);
  else if (url.startsWith("/getResumeItem/") && (method === "GET")) await getItem(RESUME_ITEM_TYPE, request, response, path.basename(url));
  else if ((url === "/saveResumeItem") && (method === "POST") && (contentType === "application/json")) await saveItem(RESUME_ITEM_TYPE, request, response);
  else if (url.startsWith("/deleteResumeItem/") && (method === "DELETE")) await deleteItem(RESUME_ITEM_TYPE, request, response, path.basename(url));
  else if (url.startsWith("/pinResumeItem/") && (method === "PUT")) await pinItem(RESUME_ITEM_TYPE, request, response, path.basename(url));
  else if ((url === "/portfolio") && (method === "GET")) await getItems(PORTFOLIO_ITEM_TYPE, request, response);
  else if (url.startsWith("/getPortfolioItem/") && (method === "GET")) await getItem(PORTFOLIO_ITEM_TYPE, request, response, path.basename(url));
  else if ((url === "/savePortfolioItem") && (method === "POST") && (contentType === "application/json")) await saveItem(PORTFOLIO_ITEM_TYPE, request, response);
  else if (url.startsWith("/deletePortfolioItem/") && (method === "DELETE")) await deleteItem(PORTFOLIO_ITEM_TYPE, request, response, path.basename(url));
  else if (url.startsWith("/pinPortfolioItem/") && (method === "PUT")) await pinItem(PORTFOLIO_ITEM_TYPE, request, response, path.basename(url));
  else if ((url === "/certifications") && (method === "GET")) await getItems(CERTIFICATION_TYPE, request, response);
  else if (url.startsWith("/getCertification/") && (method === "GET")) await getItem(CERTIFICATION_TYPE, request, response, path.basename(url));
  else if ((url === "/saveCertification") && (method === "POST") && (contentType === "application/json")) await saveItem(CERTIFICATION_TYPE, request, response);
  else if (url.startsWith("/deleteCertification/") && (method === "DELETE")) await deleteItem(CERTIFICATION_TYPE, request, response, path.basename(url));
  else if (url.startsWith("/pinCertification/") && (method === "PUT")) await pinItem(CERTIFICATION_TYPE, request, response, path.basename(url));
  else if ((url === "/customers") && (method === "GET")) await getItems(CUSTOMER_TYPE, request, response);
  else if (url.startsWith("/getCustomer/") && (method === "GET")) await getItem(CUSTOMER_TYPE, request, response, path.basename(url));
  else if ((url === "/saveCustomer") && (method === "POST") && (contentType === "application/json")) await saveItem(CUSTOMER_TYPE, request, response);
  else if (url.startsWith("/deleteCustomer/") && (method === "DELETE")) await deleteItem(CUSTOMER_TYPE, request, response, path.basename(url));
  else if (url.startsWith("/pinCustomer/") && (method === "PUT")) await pinItem(CUSTOMER_TYPE, request, response, path.basename(url));
  else if ((url === "/contacts") && (method === "GET")) await getItems(CONTACT_TYPE, request, response);
  else if (url.startsWith("/getContact/") && (method === "GET")) await getItem(CONTACT_TYPE, request, response, path.basename(url));
  else if ((url === "/saveContact") && (method === "POST") && (contentType === "application/json")) await saveContact(request, response);
  else if (url.startsWith("/answerContact/") && (method === "PUT") && (contentType === "application/json")) await answerContact(request, response, path.basename(url));
  else if (url.startsWith("/deleteContact/") && (method === "DELETE")) await deleteItem(CONTACT_TYPE, request, response, path.basename(url));
  else if (url.startsWith("/js/") && (method === "GET") && isStaticFileAllowed(url, "js", [".js"])) getJsFile(response, path.basename(url));
  else if (url.startsWith("/utilities/") && (method === "GET") && isStaticFileAllowed(url, "utilities", [".js"])) getUtilityFile(response, path.basename(url));
  else if (url.startsWith("/css/") && (method === "GET") && isStaticFileAllowed(url, "css", [".css"])) getCssFile(response, path.basename(url));
  else if (url.startsWith("/images/") && (method === "GET") && isStaticFileAllowed(url, "images", [".png", ".jpg", ".jpeg"])) getImageFile(response, path.basename(url));
  else if ((url === "/favicon.ico") && (method === "GET")) getFaviconFile(response);
  else if ((url === "/unauthorized") && (method === "GET")) getNoAccessFile(response, true);
  else getNoAccessFile(response);
});

server.listen(PORT, () => console.log(`Curriculum Vitae running on: ${BASE_URL}.`));
